---
# file: roles/common/tasks/main.yml
- name: Create aegir user
  user: name={{ aegir_user }} uid={{ aegir_uid }} shell=/bin/bash home={{ aegir_home }} groups=apache createhome=yes comment=Aegir User
